name: Test Parking Base
on:
  pull_request:
    branches:
      - master
      - dev
    types: [opened, reopened, edited]
  push:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Test via pytest
        run: pytest tests/test_flask.py
      - name: Test via isort
        run: isort --check-only --diff --profile black main/
      - name: Test via flake8
        run: flake8 main/
      - name: Test via mypy
        run: mypy main/
  correct:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Correct mistakes by black
        run: black main/
      - name: Correct mistakes by isort
        run: isort --profile black main/


